CREATE TABLE PUBLIC.USERS (
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(45) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  CONSTRAINT CONSTRAINT_4 PRIMARY KEY (USERNAME)
);

CREATE INDEX PRIMARY_KEY_4 ON PUBLIC.USERS (USERNAME);
